### ISSUE TITLE
Supervisor fails when fetching state for an app with no releases

### ISSUE THREAD

**Issue by Page-** [balena-io/balena-supervisor#1147] opened 2019-11-21 12:06 UTC
It repeatedly fails with
```
[error]   Failed to get target state for device: TypeError: Cannot read property 'length' of undefined

**Comment by Page-** [comment] 2019-11-21 12:07
State endpoint result looks like
```
{
  "local": {
    "name": "morning-dawn",
    "config": {
      "RESIN_SUPERVISOR_NATIVE_LOGGER": "true",
      "RESIN_SUPERVISOR_POLL_INTERVAL": "900000"
    },
    "apps": {
      "98939": {
        "name": "stress",
        "services": {},
        "volumes": {},
        "networks": {}
      }
    }
  },
  "dependent": {
    "apps": {},
    "devices": {}
  }
}

**Comment by CameronDiver** [comment] 2019-11-27 14:42
@Page- is there anything else you can tell me about this device? I've tried the same and not been able to reproduce, my state endpoint looks like:
```
{
  "local": {
    "name": "Ares",
    "config": {
      "RESIN_SUPERVISOR_NATIVE_LOGGER": "true",
      "RESIN_SUPERVISOR_POLL_INTERVAL": "900000"
    },
    "apps": {
      "1554024": {
        "name": "nuc-empty",
        "services": {},
        "volumes": {},
        "networks": {}
      }
    }
  },
  "dependent": {
    "apps": {},
    "devices": {}
  }
}
```

so I'm a little confused. Unless this was implcitly fixed by a later version. Which version did this occur with?

**Comment by Page-** [comment] 2019-11-27 23:24
I hit it on the supervisor bundled in balenaOS 2.44.0 and then also 10.6.6 which was the latest at the time

**Comment by CameronDiver** [comment] 2019-11-28 10:05
Ok downgrading to v10.6.6 does exhibit the problem for me, so this is now fixed. Thanks for the heads up @Page- , closing.

**Closed by CameronDiver** 2019-11-28 10:05 UTC
