### ISSUE TITLE
Does not seem to be working for purging the data volume

### ISSUE THREAD

**Issue by heri16** [balena-io/balena-supervisor#1109] opened 2019-10-04 12:27 UTC
volume "resin-data" not cleared even during doPurge with supervisor 10.3.8

https://github.com/balena-io/balena-supervisor/blob/19582a1551cac8fa58d14d536c0fabc4e157ec72/src/device-api/common.coffee#L47

**Comment by roman-mazur** [comment] 2019-10-04 14:58
Related to #1083.

**Comment by CameronDiver** [comment] 2019-10-07 13:23
@heri16 could you clarify what you're seeing? Specifically, a way to reproduce this would be helpful.

**Comment by heri16** [comment] 2019-10-15 08:36
When deploying this repo
https://github.com/zoobc/zoobc-labnet

The services are restarted and recreated, but resin-data is not removed or purged.

**Comment by heri16** [comment] 2019-10-15 08:42
@CameronDiver 

Here is my docker-compose file: https://github.com/zoobc/zoobc-labnet/blob/master/docker-compose.yml

Here is my logs when purge is triggered:
```bash
[Logs]    [10/15/2019, 4:39:19 PM] [n2] INFO[0891] ZOOBC Shutdown                               
[Logs]    [10/15/2019, 4:39:19 PM] [main] INFO[0891] ZOOBC Shutdown                               
[Logs]    [10/15/2019, 4:39:20 PM] Service exited 'main sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:20 PM] Killed service 'main sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:21 PM] Service exited 'grcpweb sha256:c6a1cbcb06c243bd30008d090abd50be98e8b879296936bd596c3626b95e44f6'
[Logs]    [10/15/2019, 4:39:21 PM] Service exited 'n2 sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:21 PM] Killed service 'grcpweb sha256:c6a1cbcb06c243bd30008d090abd50be98e8b879296936bd596c3626b95e44f6'
[Logs]    [10/15/2019, 4:39:21 PM] Killed service 'n2 sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:21 PM] Service exited 'shell sha256:b31c1585b93486ddf56ba608a8c667cab7ded3c5df36354dfb30065e3175a289'
[Logs]    [10/15/2019, 4:39:21 PM] Killed service 'shell sha256:b31c1585b93486ddf56ba608a8c667cab7ded3c5df36354dfb30065e3175a289'
[Logs]    [10/15/2019, 4:39:23 PM] Installing service 'n2 sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:23 PM] Installing service 'shell sha256:b31c1585b93486ddf56ba608a8c667cab7ded3c5df36354dfb30065e3175a289'
[Logs]    [10/15/2019, 4:39:23 PM] Installing service 'grcpweb sha256:c6a1cbcb06c243bd30008d090abd50be98e8b879296936bd596c3626b95e44f6'
[Logs]    [10/15/2019, 4:39:23 PM] Installing service 'main sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:23 PM] Installed service 'n2 sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:23 PM] Starting service 'n2 sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:23 PM] Installed service 'shell sha256:b31c1585b93486ddf56ba608a8c667cab7ded3c5df36354dfb30065e3175a289'
[Logs]    [10/15/2019, 4:39:23 PM] Starting service 'shell sha256:b31c1585b93486ddf56ba608a8c667cab7ded3c5df36354dfb30065e3175a289'
[Logs]    [10/15/2019, 4:39:24 PM] Installed service 'grcpweb sha256:c6a1cbcb06c243bd30008d090abd50be98e8b879296936bd596c3626b95e44f6'
[Logs]    [10/15/2019, 4:39:24 PM] Starting service 'grcpweb sha256:c6a1cbcb06c243bd30008d090abd50be98e8b879296936bd596c3626b95e44f6'
[Logs]    [10/15/2019, 4:39:24 PM] Installed service 'main sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:24 PM] Starting service 'main sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:26 PM] Started service 'shell sha256:b31c1585b93486ddf56ba608a8c667cab7ded3c5df36354dfb30065e3175a289'
[Logs]    [10/15/2019, 4:39:26 PM] Started service 'n2 sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:26 PM] [n2] /bin/zoobc-core --config-path=/data/zoobc-core --config-postfix=n2
[Logs]    [10/15/2019, 4:39:26 PM] Started service 'grcpweb sha256:c6a1cbcb06c243bd30008d090abd50be98e8b879296936bd596c3626b95e44f6'
[Logs]    [10/15/2019, 4:39:26 PM] Started service 'main sha256:5ca8d5d37ae5e6c5bae0b88cd87cff34da6f78352408851ea45ba6e9a9c1483f'
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] parsed scheme: ""                             system=system
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] scheme "" not registered, fallback to default scheme  system=system
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] ccResolverWrapper: sending update to cc: {[{localhost:7000 0  <nil>}] }  system=system
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] ClientConn switching balancer to "pick_first"  system=system
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] listening for http on: [::]:7001             
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0x11144f0, CONNECTING  system=system
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] grpc: addrConn.createTransport failed to connect to {localhost:7000 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:7000: connect: connection refused". Reconnecting...  system=system
[Logs]    [10/15/2019, 4:39:26 PM] [grcpweb] INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0x11144f0, TRANSIENT_FAILURE  system=system
[Logs]    [10/15/2019, 4:39:26 PM] [main] /bin/zoobc-core --config-path=/data/zoobc-core --config-postfix=main
[Logs]    [10/15/2019, 4:39:26 PM] [main] >>> /data/zoobc-core/config_main.toml...
[Logs]    [10/15/2019, 4:39:27 PM] Purged data
```

We don't see the resin-data volume being removed.

**Comment by heri16** [comment] 2019-10-15 08:43
Does purge work outside of balenaCloud?

**Comment by mwohlert** [comment] 2019-11-03 09:36
We also see the same thing. I'll investigate further tomorrow. We need this functionality.

**Comment by mwohlert** [comment] 2019-11-04 01:42
The reason for this issue is that getAllByAppId in volume manager is called with a string as appId instead of a number. This causes the lodash filter to return an empty array.
It seems to me that the appId should be a number in the first place and not any in the router.

**Comment by mwohlert** [comment] 2019-11-08 07:10
@CameronDiver What are your thoughts on this?

**Comment by mwohlert** [comment] 2019-11-13 18:58
@CameronDiver can you close this?

**Comment by CameronDiver** [comment] 2019-11-14 13:39
Odd, I'm not sure why it didn't get automatically closed with the `closes` tag. Anyway, thanks for this @mwohlert !

**Closed by CameronDiver** 2019-11-14 13:39 UTC
