### ISSUE TITLE
Supervisor unable to start cleanly after HUP (with no supervisor upgrade)

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-supervisor#1514] opened 2020-11-10 15:47 UTC
Seen on RPi3 devices moving from 2.58.3 -> 2.60.1, with errors like:

```
10.11.20 14:09:48 (+0000) Removing volume 'resin-data' 10.11.20 14:09:48 (+0000) Error removing volume 'resin-data' due to '(HTTP code 409) conflict - remove 1456319_resin-data: volume is in use - [7a13904165be63e4c9fb2bf05a09face8552c1924ba09e4894c5dc68b5c9a366] '
```

note there's no supervisor upgrade between these versions of balenaOS

**Comment by 20k-ultra** [comment] 2020-11-30 22:09
I just performed this upgrade both from 2.56.0+rev1 to 2.60.0+rev1 on rpi4 and my containers stopped. No mention of try to delete a volume in use. I think there's something going on with where the Supervisor decides to just delete the current release and in some instances there's a volume in use so that error is logged.

**Comment by 20k-ultra** [comment] 2020-12-01 20:58
Basically, [applyTargetState](https://github.com/balena-io/balena-supervisor/blob/fab864545ac0b9d73db39ba0596544fb3eab2a51/src/device-state.ts#L729) thinks there is something different about the current state and the target state since we always see "Finished applying target state" after our containers/networks/volumes get removed. I'm just unable to load a debug build onto my device to provide more logging since HUP won't run my livepush container. I am going to set a different SV version and then see if HUP overrides that too.

**Comment by 20k-ultra** [comment] 2020-12-02 04:36
Thankfully I can set a SV version and perform a host update and it will be persisted so I can run debug builds. I think I've discovered what the issue is though and might be related to 2.60 using a new location for the Supervisor sql file so the Supervisor performs a "clean up" since it cannot find a database then on first run which causes it to delete the running containers. That's why on restart everything is fine because the SV creates a db file in the new location and everything works as normal.

I saw sql files in /mnt/data/resin-data/resin-supervisor and /mnt/data/resin-supervisor but have to see which the Supervisor is trying to use and if in balenaOS 2.60 it is moving the db location from under the SV.

**Comment by 20k-ultra** [comment] 2020-12-02 20:22
I provisioned balenaOS 2.56 onto my device and from the host noted the modified timestamp for ``` /mnt/data/resin-data/resin-supervisor/database.sqlite```. Then upgraded to 2.60 and checked the data partition again and saw that in addition to the previous sqlite file there was another in ```/mnt/data/r/resin-supervisor/database.sqlite```.  The timestamp for this sqlite file is a month old though.

At this point I'm experiencing the bug so I restart the Supervisor to fix it. After restarting I checked the timestamp of the new sqlite file that gets added in 2.60 and it is in fact being used now because the timestamp was updated but the previous one was not.

This confirms that the Supervisor prior to 2.60 is using ```/resin-data/resin-supervisor/database.sqlite``` but on 2.60 it switches to ```/resin-supervisor/database.sqlite``` for some reason. 

The database path the Supervisor uses is set with: https://github.com/balena-io/balena-supervisor/blob/fab864545ac0b9d73db39ba0596544fb3eab2a51/src/lib/constants.ts#L10-L11 

I checked in 2.56 and 2.60 if `DATABASE_PATH` is ever set and it is not. Therefore, it's the /data mount that changes.

**Comment by 20k-ultra** [comment] 2020-12-02 20:34
This line from meta-balena shows /resin-data/resin-supervisor: 
https://github.com/balena-os/meta-balena/blob/8f8c54cdd458305ad040954393f7b109f1bae714/meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor#L68

so I'm trying to find out where just /resin-supervisor is coming from

**Comment by 20k-ultra** [comment] 2020-12-02 21:11
If I create a copy of the database.sqlite file found in /mnt/data/resin-supervisor/ and keep using that file it deletes the containers so I can use this to figure out what about the file is upsetting the SV. I'm still not sure where it's coming from though.

**Comment by 20k-ultra** [comment] 2020-12-04 02:06
Regardless of why/how the Supervisor switches from `/mnt/data/resin-data/resin-supervisor/database.sqlite` to `/mnt/data/resin-supervisor/database.sqlite` when the Supervisor first queries for target applications in the database the target state cache returns no applications and so the Supervisor removes the currently running application. This isn't a bug within the codebase though since this issue only happens when upgrading to balenaOS 2.60.1.

**Comment by 20k-ultra** [comment] 2020-12-07 21:06
Often when I reproduce this bug and when users share logs the following is always present..

```
...
03.12.20 21:19:40 (-0500) Applying configuration change {"SUPERVISOR_DELTA":"1","SUPERVISOR_DELTA_VERSION":"3"}
03.12.20 21:19:40 (-0500) Applied configuration change {"SUPERVISOR_DELTA":"1","SUPERVISOR_DELTA_VERSION":"3"}
...
```

maybe this is another clue for an OS level change.

**Comment by 20k-ultra** [comment] 2020-12-08 19:00
We exploring if that cause of this issue is from an OS change https://github.com/balena-os/meta-balena/commit/dc6cfa2e90b29b0fdcfc05c1b85e2196de4f950b

**Comment by 20k-ultra** [comment] 2020-12-09 21:42
It has been confirmed that the issue was from an underlying OS changed and is being fixed with https://github.com/balena-os/meta-balena/pull/2071. Closing this issue.

**Closed by 20k-ultra** 2020-12-09 21:42 UTC
Labels: High priority
