### ISSUE TITLE
Supervisor API Shutdown ignores apikey

### ISSUE THREAD

**Issue by capcarr** [balena-io/balena-supervisor#891] opened 2019-02-05 11:49 UTC
When following the example to shutdown the device via the supervisor API ([here](https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1-shutdown)), if the `apikey` is incorrect or omitted, the device will still shutdown. Is this intended behavior?

Host OS Version: balenaOS 2.29.2+rev1
Supervisor Version: 9.0.1
Device Type: Raspberry Pi 3

These commands will shutdown the device:
Incorrect `apikey`
```bash
$ curl -X POST --header "Content-Type:application/json" \
	"$BALENA_SUPERVISOR_ADDRESS/v1/shutdown?apikey=foobar"
```

Omitted `apikey`
```bash
$ curl -X POST --header "Content-Type:application/json" \
	"$BALENA_SUPERVISOR_ADDRESS/v1/shutdown"
```

**Comment by CameronDiver** [comment] 2019-02-05 12:33
I managed to reproduce this in the version of supervisor which you are using, which means it's since been fixed. This will be included in the latest balenaOS.

Thanks for the report!

**Closed by CameronDiver** 2019-02-05 12:33 UTC
Labels: Needs more investigation
